"""
Catalogue complet des devises mondiales (ISO 4217).
Utilisé pour la découverte intelligente via le moteur de recherche.
"""

GLOBAL_CURRENCY_CATALOG = [
    {"code": "AED", "name": "Dirham des Émirats", "symbol": "د.إ", "country": "Émirats Arabes Unis"},
    {"code": "AFN", "name": "Afghani Afghan", "symbol": "؋", "country": "Afghanistan"},
    {"code": "ALL", "name": "Lek Albanais", "symbol": "L", "country": "Albanie"},
    {"code": "AMD", "name": "Dram Arménien", "symbol": "֏", "country": "Arménie"},
    {"code": "ANG", "name": "Guilder des Antilles", "symbol": "ƒ", "country": "Curaçao"},
    {"code": "AOA", "name": "Kwanza Angolais", "symbol": "Kz", "country": "Angola"},
    {"code": "ARS", "name": "Peso Argentin", "symbol": "$", "country": "Argentine"},
    {"code": "AUD", "name": "Dollar Australien", "symbol": "$", "country": "Australie"},
    {"code": "AWG", "name": "Florin d'Aruba", "symbol": "ƒ", "country": "Aruba"},
    {"code": "AZN", "name": "Manat Azerbaïdjanais", "symbol": "₼", "country": "Azerbaïdjan"},
    {"code": "BAM", "name": "Marc Convertible", "symbol": "KM", "country": "Bosnie-Herzégovine"},
    {"code": "BBD", "name": "Dollar de Barbade", "symbol": "$", "country": "Barbade"},
    {"code": "BDT", "name": "Taka du Bangladesh", "symbol": "৳", "country": "Bangladesh"},
    {"code": "BGN", "name": "Lev Bulgare", "symbol": "лв", "country": "Bulgarie"},
    {"code": "BHD", "name": "Dinar de Bahreïn", "symbol": ".د.ب", "country": "Bahreïn"},
    {"code": "BIF", "name": "Franc Burundais", "symbol": "FBu", "country": "Burundi"},
    {"code": "BMD", "name": "Dollar de Bermudes", "symbol": "$", "country": "Bermudes"},
    {"code": "BND", "name": "Dollar de Brunei", "symbol": "$", "country": "Brunei"},
    {"code": "BOB", "name": "Boliviano", "symbol": "Bs.", "country": "Bolivie"},
    {"code": "BRL", "name": "Real Brésilien", "symbol": "R$", "country": "Brésil"},
    {"code": "BSD", "name": "Dollar des Bahamas", "symbol": "$", "country": "Bahamas"},
    {"code": "BTN", "name": "Ngultrum Boutanais", "symbol": "Nu.", "country": "Bhoutan"},
    {"code": "BWP", "name": "Pula du Botswana", "symbol": "P", "country": "Botswana"},
    {"code": "BYN", "name": "Rouble Biélorusse", "symbol": "Br", "country": "Biélorussie"},
    {"code": "BZD", "name": "Dollar du Belize", "symbol": "BZ$", "country": "Belize"},
    {"code": "CAD", "name": "Dollar Canadien", "symbol": "$", "country": "Canada"},
    {"code": "CDF", "name": "Franc Congolais", "symbol": "FC", "country": "RD Congo"},
    {"code": "CHF", "name": "Franc Suisse", "symbol": "CHF", "country": "Suisse"},
    {"code": "CLP", "name": "Peso Chilien", "symbol": "$", "country": "Chili"},
    {"code": "CNY", "name": "Yuan Chinois", "symbol": "¥", "country": "Chine"},
    {"code": "COP", "name": "Peso Colombien", "symbol": "$", "country": "Colombie"},
    {"code": "CRC", "name": "Colón Costaricien", "symbol": "₡", "country": "Costa Rica"},
    {"code": "CUP", "name": "Peso Cubain", "symbol": "$", "country": "Cuba"},
    {"code": "CVE", "name": "Escudo Cap-verdien", "symbol": "$", "country": "Cap-Vert"},
    {"code": "CZK", "name": "Couronne Tchèque", "symbol": "Kč", "country": "République Tchèque"},
    {"code": "DJF", "name": "Franc Djibouti", "symbol": "Fdj", "country": "Djibouti"},
    {"code": "DKK", "name": "Couronne Danoise", "symbol": "kr", "country": "Danemark"},
    {"code": "DOP", "name": "Peso Dominicain", "symbol": "RD$", "country": "République Dominicaine"},
    {"code": "EGP", "name": "Livre Égyptienne", "symbol": "£", "country": "Égypte"},
    {"code": "ERN", "name": "Nakfa Erythréen", "symbol": "Nfk", "country": "Érythrée"},
    {"code": "ETB", "name": "Birr Éthiopien", "symbol": "Br", "country": "Éthiopie"},
    {"code": "EUR", "name": "Euro", "symbol": "€", "country": "Union Européenne"},
    {"code": "FJD", "name": "Dollar de Fidji", "symbol": "$", "country": "Fidji"},
    {"code": "GBP", "name": "Livre Sterling", "symbol": "£", "country": "Royaume-Uni"},
    {"code": "GEL", "name": "Lari Géorgien", "symbol": "₾", "country": "Géorgie"},
    {"code": "GHS", "name": "Cedi Ghanéen", "symbol": "GH₵", "country": "Ghana"},
    {"code": "GIP", "name": "Livre de Gibraltar", "symbol": "£", "country": "Gibraltar"},
    {"code": "GMD", "name": "Dalasi Gambien", "symbol": "D", "country": "Gambie"},
    {"code": "GNF", "name": "Franc Guinéen", "symbol": "FG", "country": "Guinée"},
    {"code": "GTQ", "name": "Quetzal Guatémaltèque", "symbol": "Q", "country": "Guatemala"},
    {"code": "GYD", "name": "Dollar de Guyana", "symbol": "$", "country": "Guyana"},
    {"code": "HKD", "name": "Dollar de Hong Kong", "symbol": "$", "country": "Hong Kong"},
    {"code": "HNL", "name": "Lempira Hondurien", "symbol": "L", "country": "Honduras"},
    {"code": "HRK", "name": "Kuna Croate", "symbol": "kn", "country": "Croatie"},
    {"code": "HTG", "name": "Gourde Haïtienne", "symbol": "G", "country": "Haïti"},
    {"code": "HUF", "name": "Forint Hongrois", "symbol": "Ft", "country": "Hongrie"},
    {"code": "IDR", "name": "Roupie Indonésienne", "symbol": "Rp", "country": "Indonésie"},
    {"code": "ILS", "name": "Shekel Israélien", "symbol": "₪", "country": "Israël"},
    {"code": "INR", "name": "Roupie Indienne", "symbol": "₹", "country": "Inde"},
    {"code": "IQD", "name": "Dinar Irakien", "symbol": "ع.د", "country": "Irak"},
    {"code": "IRR", "name": "Rial Iranien", "symbol": "﷼", "country": "Iran"},
    {"code": "ISK", "name": "Couronne Islandaise", "symbol": "kr", "country": "Islande"},
    {"code": "JMD", "name": "Dollar Jamaïcain", "symbol": "J$", "country": "Jamaïque"},
    {"code": "JOD", "name": "Dinar Jordanien", "symbol": "د.ا", "country": "Jordanie"},
    {"code": "JPY", "name": "Yen Japonais", "symbol": "¥", "country": "Japon"},
    {"code": "KES", "name": "Shilling Kényan", "symbol": "KSh", "country": "Kenya"},
    {"code": "KGS", "name": "Som Kirghiz", "symbol": "лв", "country": "Kirghizistan"},
    {"code": "KHR", "name": "Riel Cambodgien", "symbol": "៛", "country": "Cambodge"},
    {"code": "KMF", "name": "Franc Comorien", "symbol": "CF", "country": "Comores"},
    {"code": "KPW", "name": "Won Nord-Coréen", "symbol": "₩", "country": "Corée du Nord"},
    {"code": "KRW", "name": "Won Sud-Coréen", "symbol": "₩", "country": "Corée du Sud"},
    {"code": "KWD", "name": "Dinar Koweïtien", "symbol": "د.ك", "country": "Koweït"},
    {"code": "KYD", "name": "Dollar des Îles Caïmans", "symbol": "$", "country": "Îles Caïmans"},
    {"code": "KZT", "name": "Tenge Kazakh", "symbol": "₸", "country": "Kazakhstan"},
    {"code": "LAK", "name": "Kip Laotien", "symbol": "₭", "country": "Laos"},
    {"code": "LBP", "name": "Livre Libanaise", "symbol": "£", "country": "Liban"},
    {"code": "LKR", "name": "Roupie de Sri Lanka", "symbol": "Rs", "country": "Sri Lanka"},
    {"code": "LRD", "name": "Dollar Libérien", "symbol": "$", "country": "Liberia"},
    {"code": "LSL", "name": "Loti du Lesotho", "symbol": "L", "country": "Lesotho"},
    {"code": "LYD", "name": "Dinar Libyen", "symbol": "ل.د", "country": "Libye"},
    {"code": "MAD", "name": "Dirham Marocain", "symbol": "د.م.", "country": "Maroc"},
    {"code": "MDL", "name": "Leu Moldave", "symbol": "L", "country": "Moldavie"},
    {"code": "MGA", "name": "Ariary Malgache", "symbol": "Ar", "country": "Madagascar"},
    {"code": "MKD", "name": "Denar Macédonien", "symbol": "ден", "country": "Macédoine du Nord"},
    {"code": "MMK", "name": "Kyat du Myanmar", "symbol": "K", "country": "Myanmar"},
    {"code": "MNT", "name": "Tugrik Mongol", "symbol": "₮", "country": "Mongolie"},
    {"code": "MOP", "name": "Pataca de Macao", "symbol": "P", "country": "Macao"},
    {"code": "MRU", "name": "Ouguiya Mauritanienne", "symbol": "UM", "country": "Mauritanie"},
    {"code": "MUR", "name": "Roupie Mauricienne", "symbol": "₨", "country": "Maurice"},
    {"code": "MVR", "name": "Rufiyaa des Maldives", "symbol": ".ر", "country": "Maldives"},
    {"code": "MWK", "name": "Kwacha du Malawi", "symbol": "MK", "country": "Malawi"},
    {"code": "MXN", "name": "Peso Mexicain", "symbol": "$", "country": "Mexique"},
    {"code": "MYR", "name": "Ringgit Malais", "symbol": "RM", "country": "Malaisie"},
    {"code": "MZN", "name": "Metical Mozambicain", "symbol": "MT", "country": "Mozambique"},
    {"code": "NAD", "name": "Dollar Namibien", "symbol": "$", "country": "Namibie"},
    {"code": "NGN", "name": "Naira Nigérian", "symbol": "₦", "country": "Nigeria"},
    {"code": "NIO", "name": "Córdoba Nicaraguayen", "symbol": "C$", "country": "Nicaragua"},
    {"code": "NOK", "name": "Couronne Norvégienne", "symbol": "kr", "country": "Norvège"},
    {"code": "NPR", "name": "Roupie Népalaise", "symbol": "Rs", "country": "Népal"},
    {"code": "NZD", "name": "Dollar Néo-Zélandais", "symbol": "$", "country": "Nouvelle-Zélande"},
    {"code": "OMR", "name": "Rial Omanais", "symbol": "﷼", "country": "Oman"},
    {"code": "PAB", "name": "Balboa Panaméen", "symbol": "B/.", "country": "Panama"},
    {"code": "PEN", "name": "Sol du Pérou", "symbol": "S/.", "country": "Pérou"},
    {"code": "PGK", "name": "Kina de Papouasie", "symbol": "K", "country": "Papouasie-Nouvelle-Guinée"},
    {"code": "PHP", "name": "Peso Philippin", "symbol": "₱", "country": "Philippines"},
    {"code": "PKR", "name": "Roupie Pakistanaise", "symbol": "Rs", "country": "Pakistan"},
    {"code": "PLN", "name": "Zloty Polonais", "symbol": "zł", "country": "Pologne"},
    {"code": "PYG", "name": "Guaraní du Paraguay", "symbol": "₲", "country": "Paraguay"},
    {"code": "QAR", "name": "Riyal Qatari", "symbol": "ر.ق", "country": "Qatar"},
    {"code": "RON", "name": "Leu Roumain", "symbol": "lei", "country": "Roumanie"},
    {"code": "RSD", "name": "Dinar Serbe", "symbol": "дин.", "country": "Serbie"},
    {"code": "RUB", "name": "Rouble Russe", "symbol": "₽", "country": "Russie"},
    {"code": "RWF", "name": "Franc Rwandais", "symbol": "FRw", "country": "Rwanda"},
    {"code": "SAR", "name": "Riyal Saoudien", "symbol": "﷼", "country": "Arabie Saoudite"},
    {"code": "SBD", "name": "Dollar des Îles Salomon", "symbol": "$", "country": "Îles Salomon"},
    {"code": "SCR", "name": "Roupie des Seychelles", "symbol": "₨", "country": "Seychelles"},
    {"code": "SDG", "name": "Livre Soudanaise", "symbol": "ج.س.", "country": "Soudan"},
    {"code": "SEK", "name": "Couronne Suédoise", "symbol": "kr", "country": "Suède"},
    {"code": "SGD", "name": "Dollar de Singapour", "symbol": "$", "country": "Singapour"},
    {"code": "SHP", "name": "Livre de Sainte-Hélène", "symbol": "£", "country": "Sainte-Hélène"},
    {"code": "SLL", "name": "Leone du Sierra Leone", "symbol": "Le", "country": "Sierra Leone"},
    {"code": "SOS", "name": "Shilling Somalien", "symbol": "S", "country": "Somalie"},
    {"code": "SRD", "name": "Dollar Surinamais", "symbol": "$", "country": "Suriname"},
    {"code": "SSP", "name": "Livre du Soudan du Sud", "symbol": "£", "country": "Soudan du Sud"},
    {"code": "STN", "name": "Dobra de São Tomé", "symbol": "Db", "country": "São Tomé-et-Príncipe"},
    {"code": "SVC", "name": "Colón Salvadorien", "symbol": "$", "country": "Salvador"},
    {"code": "SYP", "name": "Livre Syrienne", "symbol": "£", "country": "Syrie"},
    {"code": "SZL", "name": "Lilangeni du Swaziland", "symbol": "L", "country": "Eswatini"},
    {"code": "THB", "name": "Baht Thaïlandais", "symbol": "฿", "country": "Thaïlande"},
    {"code": "TJS", "name": "Somoni du Tadjikistan", "symbol": "SM", "country": "Tadjikistan"},
    {"code": "TMT", "name": "Manat Turkmène", "symbol": "T", "country": "Turkménistan"},
    {"code": "TND", "name": "Dinar Tunisien", "symbol": "د.ت", "country": "Tunisie"},
    {"code": "TOP", "name": "Pa'anga de Tonga", "symbol": "T$", "country": "Tonga"},
    {"code": "TRY", "name": "Lira Turque", "symbol": "₺", "country": "Turquie"},
    {"code": "TTD", "name": "Dollar de Trinité", "symbol": "TT$", "country": "Trinité-et-Tobago"},
    {"code": "TWD", "name": "Nouveau Dollar Taïwanais", "symbol": "NT$", "country": "Taïwan"},
    {"code": "TZS", "name": "Shilling Tanzanien", "symbol": "TSh", "country": "Tanzanie"},
    {"code": "UAH", "name": "Hryvnia Ukrainienne", "symbol": "₴", "country": "Ukraine"},
    {"code": "UGX", "name": "Shilling Ougandais", "symbol": "USh", "country": "Ouganda"},
    {"code": "USD", "name": "Dollar Américain", "symbol": "$", "country": "États-Unis"},
    {"code": "UYU", "name": "Peso Uruguayen", "symbol": "$U", "country": "Uruguay"},
    {"code": "UZS", "name": "Som Ouzbek", "symbol": "лв", "country": "Ouzbékistan"},
    {"code": "VES", "name": "Bolívar Vénézuélien", "symbol": "Bs.S", "country": "Venezuela"},
    {"code": "VND", "name": "Dong Vietnamien", "symbol": "₫", "country": "Vietnam"},
    {"code": "VUV", "name": "Vatu du Vanuatu", "symbol": "Vt", "country": "Vanuatu"},
    {"code": "WST", "name": "Tala Samoan", "symbol": "WS$", "country": "Samoa"},
    {"code": "XAF", "name": "Franc CFA (BEAC)", "symbol": "FCFA", "country": "Afrique Centrale"},
    {"code": "XCD", "name": "Dollar de la Caraïbe", "symbol": "$", "country": "Caraïbe Orientale"},
    {"code": "XOF", "name": "Franc CFA (BCEAO)", "symbol": "CFA", "country": "Afrique de l'Ouest"},
    {"code": "XPF", "name": "Franc CFP", "symbol": "₣", "country": "Polynésie Française"},
    {"code": "YER", "name": "Rial Yéménite", "symbol": "﷼", "country": "Yémen"},
    {"code": "ZAR", "name": "Rand Sud-Africain", "symbol": "R", "country": "Afrique du Sud"},
    {"code": "ZMW", "name": "Kwacha Zambien", "symbol": "ZK", "country": "Zambie"},
    {"code": "ZWL", "name": "Dollar Zimbabwéen", "symbol": "$", "country": "Zimbabwe"},
]
